### ISSUE TITLE
Quantifier {x,y} following nothing

### ISSUE THREAD

**Issue by freemanke** [LordVeovis/xmlrpc#2]
I think we can not change any exist code if we have not any unit test.
we should firstly add unit test to protect exist functions.

![wechat screenshot_20180723141245](https://user-images.githubusercontent.com/1439128/43060212-825dd888-8e82-11e8-95d1-62f09446924b.png)

System.ArgumentException : parsing '^(?:[a-zA-Z0-9]+|*)$' - Quantifier {x,y} following nothing.
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, TimeSpan matchTimeout, Boolean addToCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern)
   at CookComputing.XmlRpc.XmlRpcSerializer.SelectSingleNode(XmlNode node, String name)
   at CookComputing.XmlRpc.XmlRpcSerializer.DeserializeResponse(XmlDocument xdoc, Type returnType)
   at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke(Object clientObj, MethodInfo mi, Object[] parameters)
   at XmlRpcProxy69cb78c6-2314-45e2-996b-77ca47f477b7.sayHello()

**Comment by LordVeovis** [comment]
You are right, I should have tested that but I was too lazy...

I'm currently getting the unit tests from the original project back in the project and this regression was very easy to spot...
